### ISSUE TITLE
Storage provider list

### ISSUE THREAD

**Issue by jfinkhaeuser** [Joystream/substrate-runtime-joystream#11]
- [ ] Anyone can enter
- [ ] Kicked out by root

**Comment by mnaamani** [comment]
Started on in https://github.com/Joystream/substrate-runtime-joystream/pull/6

**Comment by jfinkhaeuser** [comment]
Perfect - sorry I didn't see that :)

**Comment by mnaamani** [comment]
We should probably discuss on this, I think it might be worth having a separate specialized module for each role, and have the roles module just be responsible for entry and exist, and paying out rewards.

A specialized storage_role module could have some more logic and actually pick the 'active' providers from the staked roles modules based on its own set of rules, things like error reporting could be collected there

**Comment by jfinkhaeuser** [comment]
Makes a lot of sense at this level or detail - let's do discuss this :)

For Athens, though, storage providers aren't particularly controlled - so the specialized module would be very slim.

**Comment by jfinkhaeuser** [comment]
@siman this is done with the staked roles, no? Do you still have modifications in a PR, or should I close this?

**Comment by jfinkhaeuser** [comment]
Apparently that's done.
