### ISSUE TITLE
Fix stake module and allow slashing and unstaking in the same block.

### ISSUE THREAD

**Issue by shamil-gadelshin** [Joystream/substrate-runtime-joystream#161]
Stake module public API includes:
- `initiate_slashing` - with **slash_period** parameter
- `initiate_unstaking` - with **unstaking_period** parameter

Currently, it is possible to call `initiate_unstaking` with zero unstaking_period to perform instant unstaking. But `initiate_slashing` demands greater than zero slash_period. Combined, these two functions cause an error when used together on instant unstaking with some slashes.

**Comment by mnaamani** [comment]
In #195 we now have `slash_immediate()`. So if we need to slash and inititate an unstaking in the same block, we can use this method instead of `inititate_slashing()`.

**Comment by shamil-gadelshin** [comment]
We introduced slash_immediate() API and the issue is resolved now.
https://github.com/Joystream/substrate-runtime-joystream/pull/195
