### ISSUE TITLE
Add readme

### ISSUE THREAD

**Issue by bwhm** [Joystream/substrate-runtime-joystream#22]
Create a README with instructions for how to build a node with another runtime.

**Comment by bedeho** [comment]
Yes please do, this guide could be a good start

Can we make a first stab at changing this readme? perhaps have a screenshot from the current UI, and use this as template

https://gist.github.com/PurpleBooth/109311bb0361f32d87a2

**Comment by bwhm** [comment]
[Cover](https://github.com/Joystream/design/blob/master/assets/github/substrate-runtime-joystream-repo.svg)

**Comment by mnaamani** [comment]
done in https://github.com/Joystream/substrate-runtime-joystream/pull/47
