### ISSUE TITLE
Reproducible build script

### ISSUE THREAD

**Issue by mnaamani** [Joystream/substrate-runtime-joystream#54]
The purpose of a reproducible build script is a first attempt to have a simple tool to assist council members when they come to vote on a runtime upgrade proposal.

Ideally the script would do the following:
1. clone the runtime repo, checkout the commit/branch specified by a proposal
2. Runs `docker build` to run unit tests and if successful compile the runtime wasm blob (as described in readme.)
3. If successful copy the wasm blob to local filesystem
4. Calculate and display the hash over the wasm file (using the same hash algorithm as the one produced in the runtime upgrade proposal https://github.com/Joystream/substrate-runtime-joystream/blob/ae76fc45109562ddb9415f0e333527b2b773a01d/src/governance/proposals.rs#L254 

We should make use of / reuse the Dockerfile for our node https://github.com/Joystream/substrate-node-joystream/pull/72

**Comment by mnaamani** [comment]
Having this tool ready for next council runtime upgrade would be ideal.

$50 bounty in monero for best script.

cc: @suda maybe you would be interested since you already worked on the node docker file?

**Comment by suda** [comment]
If there would be a bash script to perform step 4 (not sure is there a CLI to calculate this hash) I can easily wrap it into Docker command :)

**Comment by mnaamani** [comment]
I took a stab at this in #61
