### ISSUE TITLE
hex-literal version needs bumping in wasm/Cargo.lock

### ISSUE THREAD

**Issue by yourheropaul** [Joystream/substrate-runtime-joystream#78]
Current it fails with an error like:

```
Compiling hex-literal v0.1.4
error: proc-macro derive panicked
  --> /home/joshy/.cargo/registry/src/github.com-1ecc6299db9ec823/hex-literal-0.1.4/src/lib.rs:38:1
   |
38 | / proc_macro_expr_decl! {
39 | |     /// Macro for converting hex string to byte array at compile time
40 | |     hex! => hex_impl
41 | | }
   | |_^
   |
   = help: message: assertion failed: `(left == right)`
             left: `Some("#[allow(unused,")`,
            right: `Some("#[allow(unused")`
   = note: this warning originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error: aborting due to previous error

error: Could not compile `hex-literal`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

(See issue [#3134](https://github.com/paritytech/substrate/issues/3134) on paritytech/substrate).

A workaround is `rm wasm/Cargo.lock`, which causes the crates to be version-bumped, but I'm not sure that the side effects might be.

**Comment by bneiluj** [comment]
https://github.com/paritytech/polkadot/issues/335#issuecomment-515761136

**Comment by yourheropaul** [comment]
I guess the wasm/cargo.lock should be updated and committed?

**Comment by mnaamani** [comment]
A cleaner way would be to specify a version of hex-literal in our Cargo.toml file

**Comment by mnaamani** [comment]
But yes of course after running build, the .lock file would be updated and we can commit it into the repo.

**Comment by mnaamani** [comment]
Looks like its a good idea to go for version [0.2.0](https://github.com/paritytech/substrate/search?q=hex-literal&unscoped_q=hex-literal) but it makes more sense to bump our dependency to newer version of substrate core libraries. We need to do this for next release anyway.

**Comment by mnaamani** [comment]
This has been resolved after updating to newer version of substrate
