### ISSUE TITLE
Should we not track Cargo.lock file?

### ISSUE THREAD

**Issue by bedeho** [Joystream/substrate-runtime-joystream#86]
This is, after all, an "application", in the sense that we build a final (WASM) binary that is going to be executed, see here for convention and background

https://github.com/Joystream/joystream/issues/36#issuecomment-519165331

**Comment by mnaamani** [comment]
Good catch. We were actually tracking the [Cargo.lock](https://github.com/Joystream/substrate-runtime-joystream/blob/master/wasm/Cargo.lock) file for the wasm build.

However in substrate updates to version2 the folder structure and build procedure changed and I didn't adapt correctly. 

So will need to add it again in a new PR.

**Comment by mnaamani** [comment]
Done in #89
